Transitions for router changes #38
pets-oss/pets-front pull request #139
Opened 2021-04-03 10:10 UTC by sunny-github-acc

Added fade transitions for router changes. Also added fade transitions for nav elements on page load.

2021-04-30 07:41 UTC, saulyz requested changes
Does `AnimalDetailsPage` has transitions?
Please make some improvements and we could merge this PR.

2021-04-30 07:41 UTC, saulyz commented on src/pages/Home.tsx
> +            <div>
why we need additional `div` here?
Documentation doesn't say a word about this need.

2021-04-30 07:41 UTC, saulyz commented on src/pages/AnimalsPage.tsx
> +        <Grow in timeout={600}>
I would recommend changing transitions to "Fade". As in some pages content is being added after async fetches and this results in delayed paint. So when Grow transition progresses, some changes are added to the page. This breaks the visual flow.
Fade transition may help smoothen async things and it is more natural, unnoticeable. Which is good.

2021-04-30 08:37 UTC, sunny-github-acc commented on src/pages/Home.tsx
> +            <div>
We don't. Removed it.

2021-04-30 08:40 UTC, sunny-github-acc commented on src/pages/AnimalsPage.tsx
> +        <Grow in timeout={600}>
Noted. Changed.

2021-05-02 18:39 UTC, saulyz approved these changes

2021-05-02 18:49 UTC, saulyz approved these changes

2021-05-02 18:51 UTC, saulyz approved these changes

2021-05-03 07:04 UTC, AzisK approved these changes

2021-05-04 05:53 UTC, merged