Parameter list table #87
pets-oss/pets-front pull request #141
Opened 2021-04-03 16:20 UTC by LukasKri

Reusable table type component for animal details information in `AnimalDetails` component and event details in `EventCard` component.

**Resolves issue #87**

2021-04-03 18:16 UTC, lukaskairys commented on src/components/animal/ParamTable.tsx
> +                    borderBottom={1}
as you already have styles class for this element (root), maybe its best to write all the styles there? now some styles are passed as props and others as a class.

2021-04-03 19:01 UTC, LukasKri commented on src/components/animal/ParamTable.tsx
> +                    borderBottom={1}
Thank you for the suggestion. Do you have any ideas how to move that `borderBottom` property, because I get an error when I try to move it down to the root class.

2021-04-03 19:16 UTC, lukaskairys commented on src/components/animal/ParamTable.tsx
> +                    borderBottom={1}
Can you show me what kind of error and how did you write it up in classes object?

2021-04-05 16:17 UTC, LukasKri commented on src/components/animal/ParamTable.tsx
> +                    borderBottom={1}
I found out the solution myself and pushed new commit, thank you.

2021-04-06 21:49 UTC, povkas requested changes

2021-04-06 21:49 UTC, povkas commented on src/components/animal/AnimalDetails.tsx
>  import LayoutMultiColRow from '../layout/LayoutMultiColRow';
I would suggest to squash the unnecessary commits before opening a pull request

2021-04-06 21:49 UTC, povkas commented on src/components/animal/events/EventCard.tsx
> -    label: {
Seems like an unrelated change to the pull request, you should remove it

2021-04-06 21:49 UTC, povkas commented on src/components/animal/events/EventCard.tsx
> +    const paramsValues = [
Would encourage you to come up with a more descriptive name, paramsValues sounds very generic and does not convey anything meaningful to the person reading your code. Something like descriptionEntries would make more sense, but can be improved even more

2021-04-06 21:49 UTC, povkas commented on src/components/animal/ParamTable.tsx
> +export default function ParamTable({ items }: ParamTableProps) {
Good job! Nothing much to nitpick about

2021-04-06 21:49 UTC, povkas commented on src/components/animal/ParamTable.tsx
> +    value?: string | number | null;
By using typescript we try to shy away from the cases where a value can have multiple types, you should only accept string values. Also, you could specify the value?: string? to indicate nullable value.

2021-04-07 17:21 UTC, LukasKri commented on src/components/animal/AnimalDetails.tsx
>  import LayoutMultiColRow from '../layout/LayoutMultiColRow';
That's a very good idea, thank you. I'm afraid it's too late to fix this one as I've already made this pull request without commit squash, right? If so, I'll have a note about squashing unnecessary commits for future pull requests.

2021-04-07 17:24 UTC, LukasKri commented on src/components/animal/events/EventCard.tsx
> -    label: {
I made some changes and pushed my latest commit where I revert these changes.

2021-04-07 17:25 UTC, LukasKri commented on src/components/animal/events/EventCard.tsx
> +    const paramsValues = [
I agree and used this suggestion.

2021-04-07 17:36 UTC, LukasKri commented on src/components/animal/ParamTable.tsx
> +    value?: string | number | null;
I believe we have to accept `number` values as well, because we use this component in `EventCard.tsx` where the value of `expenses` could be a number.

I've entered `null` values, because in `AnimalDetails.tsx` the value of `comments` could a `null`, am I right on this one?

I've tried to get rid of the `null` value and type `value?: string | number;` in the interface of ParamsTableRow, but I get an error: `Type 'null' is not assignable to type 'string | number | undefined'`, so I'm out of possible solutions.

2021-04-07 17:48 UTC, povkas commented on src/components/animal/AnimalDetails.tsx
>  import LayoutMultiColRow from '../layout/LayoutMultiColRow';
Nothing prevents you from squashing it later, although for the reviewer it is easier to look at only the fixes in order to avoid reviewing the same code twice.

2021-04-07 20:00 UTC, LukasKri commented on src/components/animal/AnimalDetails.tsx
>  import LayoutMultiColRow from '../layout/LayoutMultiColRow';
I think I managed to squash all unnecessary commits, but the name of that one commit is not descriptive enough, my bad, sorry.

2021-05-06 20:32 UTC, saulyz commented
Thank you we have this feature in the codebase. We will close this PR.

2021-05-06 20:32 UTC, closed without merging