Params table #87
pets-oss/pets-front pull request #146
Opened 2021-04-06 06:42 UTC by ieva1919

2021-04-06 21:27 UTC, povkas requested changes

2021-04-06 21:27 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +const useStyles = makeStyles({
Nit.: It makes sense to keep code structure consistent throughout the project, the declaration priority might be specified explicitly, in this case, it is not (and some components have their style definitions at the top of the file), but I would still strive to make the project uniform and move the style declaration bellow the component being styled.

2021-04-06 21:27 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +                                            {item.value}
Maybe it should have a default string, when the given value is empty, for example, the event details component has "-".

2021-04-06 21:27 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +export default function Paramstable({ items }: ParamTableProps) {
React components use Pascal casing

2021-04-06 21:27 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +            <TableContainer>
I encouraged using flexbox, but in this case, using table is also good

2021-04-06 21:27 UTC, povkas commented on src/components/animal/AnimalDetails.tsx
> +    const values = [
Values is a very generic name, it's a good idea to spend some time on naming, to try to come up with something more appropriate

2021-04-07 19:03 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +                                            {item.value}
Oh, just realized this comment might not have made much sense, because you didn't use the ParamsTable component to represent data in EventCard

2021-04-07 19:20 UTC, povkas commented on src/components/animal/AnimalDetails.tsx
> +    const animalDeclarations = [
maybe animalCharacteristics would be more accurate

2021-04-07 19:20 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +    MuiBoxRoot129: {
seems like this naming it "row" would be better

2021-04-07 19:20 UTC, povkas commented on src/components/animal/filters/Paramstable.tsx
> +        <Typography>
You could specify the component being wrapped by typography via property component="div". This way you wouldn't need to wrap row with <div style={{ width: '100%' }}>

2021-04-29 14:51 UTC, saulyz commented on src/components/animal/filters/Paramstable.tsx
> +import React from 'react';
`ParamsTable` component doesn't belong here in "/animal/filters". This is not filter, rather data preview or display component. Ea. just component.
It is also idea that this component can be used flexibly in any other scope.

2021-04-29 14:51 UTC, saulyz commented on src/components/animal/filters/Paramstable.tsx
> +const useStyles = makeStyles((theme: Theme) => ({
There could be more responsive layout for the table. In XS screens label and value columns could stack on each other.

2021-04-29 14:51 UTC, saulyz commented on src/components/animal/filters/Paramstable.tsx
> +                <Typography>
I don't think you need this element in render

2021-05-06 20:33 UTC, saulyz commented
Thank you we have this feature in the codebase. We will close this PR.

2021-05-06 20:33 UTC, closed without merging