Param table component
pets-oss/pets-front pull request #147
Opened 2021-04-06 12:01 UTC by RutaUrbonaviciute

2021-04-29 14:38 UTC, saulyz requested changes

2021-05-03 20:25 UTC, RutaUrbonaviciute commented on src/components/animal/ParamTable.tsx
> +                    <Box key={index} display="flex" justifyContent="space-between" className={classes.root} p={1}>
I changed "root" class to 'item" and for the root element i don't think i need any styling, so maybe div tag with root class is not necessary in this case?

2021-05-04 06:41 UTC, saulyz requested changes
waiting for the changes

2021-05-04 06:41 UTC, saulyz commented on src/utils/animalDetails.ts
> +import { Animal } from '../graphql/types';
Let's move this code to `animals.ts`. So there will be 1 source of utilities nicely grouped in 1 file.

2021-05-04 06:41 UTC, saulyz commented on src/utils/paramTable.ts
> +import { Event } from '../graphql/types';
Let's move this code to `events.ts`. So there will be 1 source of utilities nicely grouped in 1 file.
In the future more logic can be added to render various types of event.

2021-05-05 09:01 UTC, saulyz approved these changes

2021-05-05 09:10 UTC, saulyz commented
Please update your forked branch with new `main` and then push.
Your codebase needs to be updated with the solved lint problems.

2021-05-06 20:16 UTC, merged