#172 Fix errors on the home page displayed for a non-logged in user
pets-oss/pets-front pull request #173
Opened 2021-05-10 12:15 UTC by mantasimkus

Errors on the home page are now hidden in case a user is not logged in. Resolves #172.

2021-05-12 06:46 UTC, saulyz requested changes

2021-05-12 06:46 UTC, saulyz commented on src/pages/Home.tsx
> +                {user && (
I'd use more direct check `const { isAuthenticated } = useAuth0();`
As we have no intention to do something with `user` prop further on. `user` prop here does work, but it is not a clean code.

2021-05-12 10:05 UTC, mantasimkus commented on src/pages/Home.tsx
> +                {user && (
Good point! Thank you! I've modified the code ;)

2021-05-16 18:46 UTC, saulyz approved these changes

2021-05-16 18:46 UTC, merged