Update create animal form #166
pets-oss/pets-front pull request #176
Opened 2021-05-19 13:59 UTC by linaskitm

Something wrong with description. 

![Screenshot 2021-05-19 165401](https://user-images.githubusercontent.com/70946988/118824887-e4fec480-b8c2-11eb-8103-b2d15440eb35.png)

2021-05-20 09:11 UTC, saulyz commented
Regarding your question about the screenshot - is the problem the `description` value? Normally would expect `string` with HTML and it seems we have `object`. This might depend upon the component configuration. Can't give the ready solution, but exploring https://github.com/niuware/mui-rte might help.

2021-05-21 12:38 UTC, domzic commented
mui-rte editor passes stringified object to `onSave` callback. We need to convert it to JSON object and then take `text` field.
Could you add these changes?
`onSave={data => props.onChange(JSON.parse(data).text)}`

2021-05-21 12:40 UTC, domzic requested changes

2021-05-21 12:40 UTC, domzic commented on src/components/animal/create/DetailsStep.tsx
> +                    <TextInput type="file" name="imageUrl" id="imageUrl" fullWidth />
Do not set `type="file"`. We wan't just image URL, not to upload raw image

2021-05-24 06:21 UTC, saulyz commented on src/components/animal/create/DetailsStep.tsx
> +                    <TextInput type="file" name="imageUrl" id="imageUrl" fullWidth />
@domzic sorry, there should be `type="file"` according to the last specification from the backend. So this change is actually valid. @linaskitm but the name then is not good - should not have "Url" as this is the file now.

2021-05-25 07:09 UTC, linaskitm commented on src/components/animal/create/DetailsStep.tsx
> +                    <TextInput type="file" name="imageUrl" id="imageUrl" fullWidth />
Thanks for comments, I changed the image name.  
And  `onSave={data => props.onChange(JSON.parse(data).text)}` doesn't work as expected.

2021-05-25 09:19 UTC, domzic approved these changes

2021-05-25 09:36 UTC, merged

2021-05-25 09:37 UTC, saulyz commented
Merging this PR as it has reached main objectives.
mui-rte fixes will be made on another PR.