add component PaginationRounded
pets-oss/pets-front pull request #192
Opened 2021-07-27 19:10 UTC by ieva1919

2021-07-28 11:26 UTC, saulyz requested changes
There is one suggested change and a question

2021-07-28 11:26 UTC, saulyz commented on src/utils/AuthorizedApolloProvider.tsx
> +                                return incoming;
What impact exactly this does?

2021-07-28 12:49 UTC, saulyz commented
in the screen size of 360px pagination component does not fit into a screen. Some style adjustments are needed

2021-07-28 16:20 UTC, ieva1919 commented on src/utils/AuthorizedApolloProvider.tsx
> +                                return incoming;
By default fetchMore appends new items to the bottom. This change makes new items replace old ones. https://www.apollographql.com/docs/react/pagination/core-api/#defining-a-field-policy

2021-08-04 15:39 UTC, ieva1919 commented on src/components/animal/PaginationRounded.tsx
> +                    rowsPerPage={pageSize}
But rowsPerPage is props of the component TablePagination. I can not change the title because then it does not work.

2021-08-11 09:37 UTC, saulyz approved these changes

2021-08-11 13:03 UTC, merged