Animal create/edit features
pets-oss/pets-front pull request #207
Opened 2021-09-22 12:15 UTC by saulyz

WIP. Before the mutations

2021-09-22 12:16 UTC, saulyz commented
seems like a dirty source branch... Some irrelevant commits are pulled from the history

2021-09-22 13:55 UTC, rikius requested changes

2021-09-22 13:55 UTC, rikius commented on src/components/animal/create/AnimalForm.tsx
> +            formData.details.birthDate = filterBirthDateField(formData.details?.birthDate);
not seeing why we need to change birthDate here.

2021-09-22 13:55 UTC, rikius commented on src/components/animal/create/AnimalForm.tsx
> +            const animalCopy = Object.assign({}, data.animal, {
not seeing why we need to convert data here.

2021-09-22 13:55 UTC, rikius commented on src/components/animal/create/DetailsStep.tsx
>                          name="details.birthDate"
we can convert data to correct view format here.

2021-09-24 09:54 UTC, saulyz commented
waiting for the Backend team changes regarding type structures

2021-09-24 15:32 UTC, rikius approved these changes

2021-09-24 15:32 UTC, rikius commented on src/components/animal/create-update/AnimalForm.tsx
> +            reset(getDefaultFormValues(animal));
remember why we need to have this reset?

2021-10-01 14:46 UTC, rikius approved these changes

2021-10-06 13:14 UTC, merged