Integrate linting tools:
pets-oss/pets-front pull request #37
Opened 2021-01-14 16:44 UTC by domzic

- Setup Prettier and eslint;
 - Format src code;
 - Add linting job to github actions

2021-01-14 16:45 UTC, domzic commented on .github/workflows/github-pages.yml
> +          key: ${{ github.sha }}z
Remove

2021-01-15 09:28 UTC, rikius requested changes
need to fix those small issues, but also it might be merged without them, just remove `z` letter in one of changes.

2021-01-15 09:28 UTC, rikius commented on .editorconfig
> +indent_size = 2
let's keep it 4 spaces.

2021-01-15 09:28 UTC, rikius commented on .editorconfig
> +indent_size = 2
let's keep it 4 spaces.

2021-01-15 09:28 UTC, rikius commented on src/App.tsx
> +import CssBaseline from '@material-ui/core/CssBaseline';
Can we sort all those imports?

2021-01-15 09:37 UTC, domzic commented on src/App.tsx
> +import CssBaseline from '@material-ui/core/CssBaseline';
It's sorted

2021-01-15 10:07 UTC, saulyz commented
Some files are still with 2 space format.
tsconfig.json, .prettierrc

2021-01-15 10:11 UTC, saulyz approved these changes

2021-01-15 11:19 UTC, rikius approved these changes

2021-01-15 11:23 UTC, merged