Basic Animal details page / Layout mock, Closes #42
pets-oss/pets-front pull request #43
Opened 2021-01-18 12:53 UTC by saulyz

Just trying to create a page UI basis for further developments, refinements.
Some responsive tweaks are made for page spacing and typography.

2021-01-18 13:25 UTC, benNek requested changes

2021-01-18 13:25 UTC, benNek commented on src/App.tsx
> +            marginTop: 56 + 16,
why the calculation is needed? also the values seems a bit random

2021-01-18 13:25 UTC, benNek commented on src/components/EventList.tsx
> +            color: 'white',
shouldnt we use all colors from palette?

2021-01-18 13:25 UTC, benNek commented on src/components/EventList.tsx
> +                    <>
In general, keys are useful for list items to let React know that element can change their position and during reconcilation process not completely throw it out and render from scratch.

[Take a look what code similar to yours generates](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAYTgWwA4IKZigCgEpEBvAKEUQCdsoQqkBtARgBpEAmdgZnYBYAugDo0AQwz58MACbEAvAD5E-CpUQAeBarWkZiAIRy5iAAyIAZOY0ALKogD0CgL6Jta9QEko2NIgDW2ACeciQyLo5u6hGUhIQA3GROZGSgkLAIiF4-RKSqNHQMypHSMABuCgAq2ADOUFEl5ZSqhIlAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=)

Only the top most element should have a key, it doesn't provide any value for others, so you either should switch it to React.Fragment with key or use regular div element

2021-01-18 13:25 UTC, benNek commented on src/components/EventList.tsx
> +                                    <>
<> is useless in here, you can use <Typography /> directly

2021-01-18 13:25 UTC, benNek commented on src/components/LayoutTwoCol.tsx
> +    children: {
the usage becomes very weird and unintuitive the way these props are passed. It would look way better if it had regular 2 props firstColumnItem and secondColumnItem (or whatever you'd like to name it)

2021-01-18 13:36 UTC, rikius approved these changes

2021-01-18 13:36 UTC, rikius commented on src/App.tsx
> +            marginTop: 56 + 16,
why not using the end sum?

2021-01-18 13:36 UTC, rikius commented on src/App.tsx
> +            marginTop: 56 + 16,
`marginTop: 56 + theme.spacing(16)`

2021-01-18 13:36 UTC, rikius commented on src/components/EventList.tsx
> +                        {index !== 0 ? <Divider component="li" /> : null}
Missing key attribute in the divider element or extract key to the top level.

2021-01-18 13:52 UTC, domzic commented on src/App.tsx
> +            marginTop: 56 + 16,
@rikius you mean theme.spacing(2), because base value is 8px

2021-01-18 13:52 UTC, rikius commented on src/components/LayoutTwoCol.tsx
> +    children: {
I have suggested dynamic child selection.

2021-01-18 13:55 UTC, domzic commented on src/components/EventList.tsx
> +            color: 'white',
`theme.palette.common.white`

2021-01-18 14:07 UTC, domzic commented on src/components/LayoutTwoCol.tsx
> +function LayoutTwoCol({ children }: Props) {
Do we really want to create such layouting components?

1. It's not flexible since we cannot change spacing, column widths. 18px spacing is kind of big, so we couldn't use this component for mobile. What if I would like to make second column 2x smaller? At the end of the day I would use material ui Grid directly with way more flexibility on alignments and spacings
2. Components will become messy. If we would need to include more components like this, we would end up constructing objects, not nesting react components

2021-01-18 14:07 UTC, domzic commented on src/pages/Animal.tsx
> +            color: 'dimGray',
Use palette colors `theme.palette.grey.x`

2021-01-18 21:04 UTC, saulyz commented on src/components/EventList.tsx
> +                                    <>
doesn't seem to work. Compiler requires single root el.

2021-01-18 22:11 UTC, saulyz commented on src/components/LayoutTwoCol.tsx
> +function LayoutTwoCol({ children }: Props) {
turning it to more flexible version

2021-01-18 22:16 UTC, saulyz commented on src/components/LayoutTwoCol.tsx
> +    children: {
converting into more flexible version

2021-01-18 22:20 UTC, saulyz commented on src/components/EventList.tsx
> +                                            ' — Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor…'
will be

2021-01-19 07:15 UTC, benNek commented on src/components/EventList.tsx
> +                    <div key={`event-list${item}`}>
just FYI, event-list is redundant in key and item number is more than sufficient

2021-01-19 07:15 UTC, benNek approved these changes

2021-01-19 07:23 UTC, domzic approved these changes

2021-01-19 08:00 UTC, merged