populate animal details page
pets-oss/pets-front pull request #53
Opened 2021-02-02 19:01 UTC by padomaitis

2021-02-03 12:50 UTC, rikius requested changes

2021-02-03 12:50 UTC, rikius commented on src/pages/AnimalDetails.test.tsx
> +            breed: 'Rodezijos ridžbekai',
better to have English namings.

2021-02-03 12:50 UTC, rikius commented on src/pages/AnimalDetails.tsx
> +    const birthDay = animal.details?.birthDate ? getAnimalAge(Number(animal.details.birthDate)) : '';
Don't specify type here, better in Utility class `getAnimalAge`.

2021-02-04 17:16 UTC, padomaitis commented on src/pages/AnimalDetails.test.tsx
> +            breed: 'Rodezijos ridžbekai',
fixed

2021-02-04 17:16 UTC, padomaitis commented on src/pages/AnimalDetails.tsx
> +    const birthDay = animal.details?.birthDate ? getAnimalAge(Number(animal.details.birthDate)) : '';
fixed

2021-02-04 19:55 UTC, rikius approved these changes

2021-02-05 06:10 UTC, merged