Add animal and event cards
pets-oss/pets-front pull request #60
Opened 2021-02-19 13:07 UTC by PPrakapavicius

2021-02-23 10:06 UTC, rikius approved these changes

2021-02-26 09:16 UTC, domzic requested changes

2021-02-26 09:16 UTC, domzic commented on src/components/animal/AnimalCard.tsx
> +        width: 280,
Why are you setting width if this component is wrapped in grid item with breakpoints `xs={10} md={6} lg={3}` ?

2021-02-26 09:16 UTC, domzic commented on src/components/animal/EventCard.tsx
> +    root: {
Same here - material ui grid already does that

2021-02-26 09:16 UTC, domzic commented on src/components/animal/AnimalCard.tsx
> +        return `${process.env.PUBLIC_URL}/logo192.png`;
Use `config.ts`

2021-03-02 09:09 UTC, PPrakapavicius commented on src/components/animal/EventCard.tsx
> +    root: {
Will set width to 100% here as now card's width depends on it's content

2021-03-02 09:18 UTC, domzic approved these changes

2021-03-02 09:43 UTC, merged