Add recent animals and events to home page
pets-oss/pets-front pull request #76
Opened 2021-03-15 10:30 UTC by padomaitis

2021-03-16 14:41 UTC, rikius requested changes

2021-03-16 14:41 UTC, rikius commented on src/components/layout/HomePageCarouselContainer.tsx
> +    const carouselItems = isDesktop ? [itemsToRender.slice(0, 3), itemsToRender.slice(3, 6)] : [];
move this function to renderItems method.
```suggestion
    
```

2021-03-16 14:41 UTC, rikius commented on src/components/layout/HomePageCarouselContainer.tsx
> +            return carouselItems.map((carouselItem, index) => (
put it here: 
```suggestion
            const carouselItems = isDesktop ? [itemsToRender.slice(0, 3), itemsToRender.slice(3, 6)] : [];
            return carouselItems.map((carouselItem, index) => (
```

2021-03-16 14:41 UTC, rikius commented on src/components/layout/RecentAnimalsContainer.tsx
> +} as const;
This is an object not a constant. Create an interface that's representing MobileProps properties.

2021-03-16 14:41 UTC, rikius commented on src/components/layout/RecentAnimalsContainer.tsx
> +} as const;
This is an object not a constant. Create an interface that's representing desktop properties.

2021-03-16 14:41 UTC, rikius commented on src/graphql/queries/animal-details.graphql
> +            species {
You have changed GraphQL structure, please make sure that you updated types too:

```
npm run codegen
```

2021-03-16 14:41 UTC, rikius commented on src/graphql/queries/animal-list.graphql
> +            species {
You have changed GraphQL structure, please make sure that you updated types too:

```
npm run codegen
```

2021-03-16 14:41 UTC, rikius commented on src/utils/animal.ts
> +    const date1 = parseInt(animal1.modTime as string, 10);
Is this is an integer type? I guess you first need to convert it to Date type then pick UNIX timestamp
```
new Date('2012.08.10').getTime() / 1000
````
Later you can use them how to sort.


From the documentation, you can't convert it to that.
```
modTime: String
Modification time

The String scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.

scalar String
```

2021-03-16 14:41 UTC, rikius commented on src/utils/events.ts
> +    const date1 = parseInt(event1.dateTime as string, 10);
Is this is an integer type? I guess you first need to convert it to Date type then pick UNIX timestamp
```
new Date('2012.08.10').getTime() / 1000
````
Later you can use them how to sort.

From the documentation, you can't convert it to that.

```
dateTime: String
Event date

The String scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.

scalar String
```

2021-03-16 15:56 UTC, padomaitis commented on src/components/layout/HomePageCarouselContainer.tsx
> +            return carouselItems.map((carouselItem, index) => (
fixed

2021-03-16 15:57 UTC, padomaitis commented on src/components/layout/RecentAnimalsContainer.tsx
> +} as const;
replaced with Record<string, GridSize>

2021-03-16 15:57 UTC, padomaitis commented on src/graphql/queries/animal-details.graphql
> +            species {
done

2021-03-16 15:58 UTC, padomaitis commented on src/utils/animal.ts
> +    const date1 = parseInt(animal1.modTime as string, 10);
looks like modTime is timestamp

2021-03-18 12:06 UTC, padomaitis commented on src/components/layout/HomePageCarouselContainer.tsx
> +    const carouselItems = isDesktop ? [itemsToRender.slice(0, 3), itemsToRender.slice(3, 6)] : [];
fixed

2021-03-18 12:07 UTC, padomaitis commented on src/components/layout/RecentAnimalsContainer.tsx
> +} as const;
as as above

2021-03-18 12:07 UTC, padomaitis commented on src/graphql/queries/animal-list.graphql
> +            species {
done

2021-03-18 12:07 UTC, padomaitis commented on src/utils/events.ts
> +    const date1 = parseInt(event1.dateTime as string, 10);
same as above

2021-03-18 16:43 UTC, padomaitis commented on src/components/layout/RecentEventsContainer.tsx
> +        <Box marginTop={2} className={classes.root}>
fixed

2021-03-18 16:45 UTC, padomaitis commented on src/components/layout/RecentAnimalsContainer.tsx
> +    const mediaProps = isDesktop ? DesktopProps : MobileProps;
I removed mediaProps, and replaced  with <AnimalCard animal={animal} key={animal.id} xs={12} md={4} lg={4} />, as I think AnimalCard in different places can have different xs md and lg values,

2021-03-18 16:46 UTC, padomaitis commented on src/components/layout/HomePageCarouselContainer.tsx
> +        fontSize: 24,
fixed

2021-03-18 16:49 UTC, padomaitis commented on src/components/layout/HomePageCarouselContainer.tsx
> +        [theme.breakpoints.down('md')]: {
replaced with mt

2021-03-19 06:32 UTC, domzic approved these changes

2021-03-22 13:34 UTC, merged