New event dialog created
pets-oss/pets-front pull request #96
Opened 2021-03-26 07:45 UTC by migleankstutyte

2021-03-26 10:51 UTC, lukaskairys commented on src/components/animal/events/AnimalEventDialog.tsx
> +        id: Math.floor(Math.random() * 100) + 1,
`Math.random()` does not ensure unique id generation, it would be better to use something like "uuid" npm package, or maybe some other library is used in this project

2021-03-26 10:52 UTC, lukaskairys commented on src/components/animal/events/AnimalEventDialog.tsx
> +    const [error, setErrors] = useState({});
maybe state name "errors" would be more meaningful, saying this is not a single error?

2021-05-06 07:10 UTC, benNek requested changes
Good job, however the input handling looks a bit brittle right now and hard to maintain. I'd fix that :)

2021-05-06 07:10 UTC, benNek commented on src/components/animal/events/AnimalEventDialog.tsx
> +            if (name === inputsNames[2]) {
although storing values in array does provide a lot of flexibiility, but this is the ugly side of it. If you would add another input just before this one, then validation wouldn't work anymore. That's why it's actually more popular to store values in different variables with correct naming.

You can take a look at Formik and yup for inspiration

2021-05-06 07:10 UTC, benNek commented on src/components/animal/events/AnimalEventDialog.tsx
> +        setErrors(errors);
So this both returns the errors and setErrors state. In case the errors is empty, `setErrors({})` would be called twice (here and line 82). It's better to jo just return the errors and handle `setErrors` in form submit. Other way around works too

2021-05-06 07:10 UTC, benNek commented on src/components/animal/events/AnimalEventDialog.tsx
> +    const TypeOptions = [
you should move constants outside of Functional components, as they are being reinitialized on every re-render

2021-05-06 07:12 UTC, benNek commented on src/components/animal/events/AnimalEventDialog.tsx
> +    const [inputs, setInputs] = useState<any>(initialValues);
is it really any? I think it should be `string | number`

2021-05-06 13:06 UTC, closed without merging